name: Token Launchpad Form
description: Information needed to Launch a token on the Soonaverse
title: "[TLP]: "
labels: ["TLP"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Please provide the following information to apply to launch a token on the Soonaverse LaunchPad. Please note that the information you are providing here is in a public repository. Do not disclose information in this form you would like to keep private. All information used to verify your identity is privately held by a 3rd part vendor. We do not see or retain that information. If you have previously filled out the application form for your project, please refrain from applying again.
  - type: input
    id: tlp-email
    attributes:
      label: Email
      description: Enter your Email Address
      placeholder: "email@address.com"
    validations:
      required: true
  - type: input
    id: tlp-company-name
    attributes:
      label: Company Name
      description: Please enter your company name
      placeholder: "Company Name"
    validations:
      required: true
  - type: input
    id: tlp-token-link
    attributes:
      label: Token Link
      description: Please fill up link for created token on Soonaverse
      placeholder: "Soonaverse Token URL"
    validations:
      required: true
  - type: dropdown
    id: tlp-position
    attributes:
      label: Your Position
      description: Please confirm your position with this Project
      options:
        - CEO
        - Founder / Co-Founder
        - Other (Please describe in comments)
    validations:
      required: true
  - type: input
    id: tlp-name
    attributes:
      label: Name
      description: Please enter your name.
      placeholder: "Name"
    validations:
      required: true
  - type: dropdown
    id: tlp-sale
    attributes:
      label: Have you already done a public sale?
      description: Have your tokens already been sold outside of the Soonaverse?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Files and other information
      description: Please provide links to any other information. If you entered "Other" for any dropdowns above please enter details here.
      render: shell
